version: '3'

services:

  petclinic:
    container_name: pets
    image: petclinic:latest
    ports: 
      - "8081:8081"
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    container_name: pets-mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
